version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: proyecto-integrador
    restart: always
    networks:
      - spring

  proyecto-integrador-back:
    container_name: proyecto-integrador-back
    #image: aguzf/usuarios:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3307
      DB_DATABASE: proyecto-integrador
      DB_USERNAME: root
      DB_PASSWORD: sasa
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

networks:
  spring:
    name: spring